springfox:
  documentation:
    enabled: false

knife4j:
  enable: true # 停用Swagger文档

# 配置日志级别
logging:
  level:
    org:
      springframework: warn
    com:
      alsritter: info
  file:
    path: "./logs"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"