server:
  port: 7758
  servlet:
    # 设置响应为 utf-8
    encoding:
      charset: utf-8
    context-path: /api/ # 设置全局的访问路径前面有 api

spring:
  profiles:
    active: '@profiles.active@'   # 这里引用的是 pom.xml 中配置的 key
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf8&useSSL=true&useServerPrepStmts=true
    username: root
    password: root
    hikari:
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: "SELECT 1"
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: "hikariCP"
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（ms）
    timeout: 10000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    # 注意：别忘了设置缓存用的是 redis
  cache:
      type: redis

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

